// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateWatchHistory = { channel_id: string, channel_name: string, channel_avater_url: string, channel_subscribers_count: bigint, video_id: string, video_title: string, video_description: string, video_duration: bigint, video_tags: Array<string>, published_at: bigint, view_count: bigint, watch_duration_seconds: bigint, session_start_date: bigint, session_end_date: bigint, video_thumbnail_url: string, };
