// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateWatchHistoryVideo = { id: string, title: string, description: string, thumbnailUrl: string, tags: Array<string>, viewCount: bigint, duration: bigint, publishedAt: bigint, };
