// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateWatchHistoryChannel } from "./CreateWatchHistoryChannel";
import type { CreateWatchHistoryVideo } from "./CreateWatchHistoryVideo";

export type CreateWatchHistoryRequest = { watchDurationSeconds: number, sessionStartDate: number, sessionEndDate: number, channel: CreateWatchHistoryChannel, video: CreateWatchHistoryVideo, };
