// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateWatchHistoryChannel } from "./CreateWatchHistoryChannel";
import type { CreateWatchHistoryVideo } from "./CreateWatchHistoryVideo";

export type CreateWatchHistoryRequest = { watch_duration_seconds: number, session_start_date: number, session_end_date: number, channel: CreateWatchHistoryChannel, video: CreateWatchHistoryVideo, };
