// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateWatchHistoryChannel = { id: string, name: string, avater_url: string, subscribers_count: number, };
