// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Channel = { id: string, name: string, url: string, is_subscribed: boolean, subscribers_count: bigint, added_at: bigint, };
