// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelResponse = { avatar_endpoint: string, id: string, name: string, url: string, is_subscribed: boolean, subscribers_count: number, added_at: number, };
