// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateWatchHistoryVideo = { id: string, title: string, description: string, thumbnail_url: string, tags: Array<string>, likes_count: number, view_count: number, comments_count: number, duration: number, published_at: number, };
