// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";

export type GetVideosResponse = { id: string, channel: Channel, url: string, thumbnail_endpoint: string, title: string, description: string, watch_counter: bigint, duration_seconds: bigint, likes_count: bigint, view_count: bigint, comments_count: bigint, published_at: bigint, tags: Array<string>, added_at: bigint, };
