// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { Video } from "./Video";

export type GetWatchHistoryResponse = { id: string, video: Video, channel: Channel, watch_duration_seconds: bigint, session_start_date: bigint, session_end_date: bigint, added_at: bigint, };
