// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OverviewResponse = { total_watch_time_seconds: number, total_videos_watched: number, total_unique_videos_watched: number, total_channels: number, total_tags: number, average_watch_time_per_session_seconds: number, };
