// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelResponse } from "./ChannelResponse";

export type VideoResponse = { thumbnail_endpoint: string, tags: Array<string>, channel: ChannelResponse | null, id: string, url: string, title: string, description: string, watch_counter: number, duration_seconds: number, likes_count: number, view_count: number, comments_count: number, published_at: number, added_at: number, };
