// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Video = { id: string, url: string, title: string, description: string, watch_counter: bigint, duration_seconds: bigint, likes_count: bigint, view_count: bigint, comments_count: bigint, published_at: bigint, added_at: bigint, };
