// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoResponse } from "./VideoResponse";

export type WatchHistoryResponse = { video: VideoResponse, id: string, watch_duration_seconds: number, session_start_date: number, session_end_date: number, added_at: number, };
