// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { Video } from "./Video";

export type WatchHistoryResponse = { video: Video, channel: Channel, id: string, watch_duration_seconds: number, session_start_date: number, session_end_date: number, added_at: number, };
