[project]
name = "generate-data"
version = "0.1.0"
description = "Generate fake data for testing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker==37.5.3",
    "rich==14.1.0",
]
