from faker import Faker

TEN_YEARS = 10 * 365 * 24 * 60 * 60

MIN_VIDEO_PUBLISHED_AT = int(1e4)
MAX_VIDEO_PUBLISHED_AT = TEN_YEARS
MIN_SESSION_START = int(1e5)
MAX_SESSION_START = int(1e6)

MIN_SESSION_END = 0
MAX_SESSION_END = int(1e3)

fake = Faker()
